accounting_endpoint: https://api.xero.com/api.xro/2.0/Contacts
client_id: D854ADD27C42461FBFDB222181A42398
client_secret: UUeWiFyLyNbFvE8qF2L5Cf28-S7iuxEj8Y2e-tpApjGRZ3Lp
refresh_token: CC-5NDCZ_jQsl5A7UHsfmeTzBIU73tAl_sdMq2LuFag
tenant_id: fa8b8c86-1f49-4816-a867-90742c43f327
tokenapi_url: https://identity.xero.com/connect/token
user_endpoint: https://api.xero.com/api.xro/2.0/Users
